services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--log.level=TRACE"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--metrics.prometheus=true"
      - "--providers.file.filename=/opt/traefik.yml"
      - "--entryPoints.web.observability.metrics=true"
      - "--certificatesresolvers.certresolver.acme.email=wiphilip@ethz.ch"
      - "--certificatesresolvers.certresolver.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.certresolver.acme.tlschallenge=true"
    ports:
      - "443:443"
      - "80:80"
    expose: 
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - acme:/acme
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`${HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      traefik.http.routers.dashboard.middlewares: ${AUTH_MIDDLEWARE}
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.tls.certresolver: certresolver
      traefik.frontend.headers.passHostHeader: true
      traefik.http.services.dashboard.loadbalancer.server.port: 8080
    networks:
      - scopemarchiver_network
    configs:
      - source: traefik.yml
        target: /opt/traefik.yml
    secrets:
      - prometheus_auth


  authentik-proxy:
    image: ghcr.io/goauthentik/proxy
    ports:
      - 9002:9000
      - 9443:9443
    restart: unless-stopped
    environment:
      AUTHENTIK_HOST: ${AUTHENTIK_HOST}
      AUTHENTIK_INSECURE: ${AUTHENTIK_INSECURE}
      AUTHENTIK_TOKEN:
      AUTHENTIK_LOG_LEVEL: info
    entrypoint: ["/bin/sh", "-c", "export AUTHENTIK_TOKEN=$(cat /run/secrets/authentik_token) && ./proxy"]

    networks:
      - scopemarchiver_network
    secrets:
      - authentik_token
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.authentik.rule: (Host(`host.docker.internal`) || Host(`${HOST}`)) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.tls: ""
      # `authentik-proxy` refers to the service name in the compose file.
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

configs:
  traefik.yml:
    content: |
      http:
        routers:
          external-api-router:
            rule: "Host(`$HOST`) && PathPrefix(`/`)"
            entryPoints:
              - websecure
            tls: ""
            service: 
              external-api-minio
        services:
          external-api-minio:
            loadBalancer:
              servers:
                - url: "https://${MINIO_ENDPOINT}"
              passHostHeader: true
secrets:
  authentik_token:
    file: ./.secrets/authentik_token
  prometheus_auth:
    file: ./.secrets/.htpasswd_prom

volumes:
  acme: